apiVersion: v1
kind: Service
metadata:
    name: service-cloned-2
    namespace: web
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  type: NodePort
  selector:
    app: service-cloned-2
---
apiVersion: apps/v1
metadata:
  name: service-cloned-2
  labels:
      app: service-cloned-2
  namespace: web
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-cloned-2
  template:
    metadata:
      labels:
        app: service-cloned-2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
          name: cloned-2
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: web-clone-2