apiVersion: v1
kind: Service
metadata:
    name: service-cloned-1
    namespace: web
spec:
  ports:
  - port: 80
    name: web
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  type: NodePort
  selector:
    app: service-cloned-1
---
apiVersion: apps/v1
metadata:
  name: service-cloned-1
  labels:
      app: service-cloned-1
  namespace: web
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-cloned-1
  template:
    metadata:
      labels:
        app: service-cloned-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
          - name: my-pvc-nfs
            mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
          name: cloned-1
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: web-clone-1