apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
 name: snap-datalake
 namespace: 4-webinar
spec:
 volumeSnapshotClassName: csi-snapclass
 source:
    persistentVolumeClaimName: datalake
